wandb_version: 1

epochs:
  desc: null
  value: 50
_wandb:
  desc: null
  value:
    python_version: 3.6.9
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1687359267.886706
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.6.9
      5: 0.15.4
      8:
      - 5
